apiVersion: v1
kind: Service
metadata:
  name: kairu
  labels:
    app: kairu
spec:
  type: ClusterIP
  selector:
    app: kairu
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
